# Generated by Django 4.1 on 2023-04-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0003_pv_member_others_rooms_alter_pv_member_others"),
    ]

    operations = [
        migrations.AddField(
            model_name="pv_message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat_images/"),
        ),
    ]
