# Generated by Django 4.1 on 2023-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0005_pv_message_file_alter_pv_message_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="pv_message",
            name="dif",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
