# Generated by Django 4.1 on 2023-06-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0006_pv_message_dif"),
    ]

    operations = [
        migrations.AddField(
            model_name="pv_message",
            name="edited",
            field=models.BooleanField(null=True),
        ),
    ]
