# Generated by Django 4.1 on 2023-06-16 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private', '0007_pv_message_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pv_message',
            name='image',
        ),
        migrations.AlterField(
            model_name='pv_message',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pv_message',
            name='file',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Channel_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.IntegerField(unique=True)),
                ('admin', models.ManyToManyField(related_name='channel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Channel_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('file', models.CharField(max_length=256, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_room', to='private.channel_room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.AddField(
            model_name='pv_member',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='user_channels', to='private.channel_room'),
        ),
    ]
