# Generated by Django 4.1 on 2023-06-24 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private', '0008_remove_pv_message_image_alter_pv_message_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv_member',
            name='display_name',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=256),
        ),
        migrations.AlterField(
            model_name='pv_member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
