# Generated by Django 4.1.6 on 2023-06-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0009_pv_member_display_name_alter_pv_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv_member',
            name='bio',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='pv_member',
            name='email',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='pv_member',
            name='display_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
