# Generated by Django 4.1.3 on 2023-08-02 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0010_pv_member_bio_pv_member_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pv_member',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='pv_member',
            name='email',
        ),
        migrations.AlterField(
            model_name='pv_member',
            name='display_name',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=256),
        ),
    ]
