# Generated by Django 3.2.12 on 2023-08-15 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0012_auto_20230815_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv_member',
            name='display_name',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL), max_length=256),
        ),
    ]
