# Generated by Django 4.1 on 2023-03-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channel', '0002_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_room',
            name='bio',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='channel_room',
            name='password',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
